name: build
on:
  pull_request:
    type: [opened]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get upgrade
      - run: sudo apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build build-essential cmake libasound2-dev wget libspdlog-dev
      - run: wget http://www.music.mcgill.ca/~gary/rtaudio/release/rtaudio-5.2.0.tar.gz
      - run: tar -xzvf rtaudio-5.2.0.tar.gz && cd rtaudio-5.2.0.tar.gz
      - run: ./configure --with-alsa
      - run: mkdir build && cd build
      - run: cmake ../
      - run: make -j 4
      - run: sudo make install && sudo ldconfig && cd ../../
      - run: pip3 install meson
      - run: meson setup build
      - run: ninja -C build
