name: cpplint
on:
  pull_request:
    type: [opened]

jobs:
  build:
    name: cpplint
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install python3 python3-pip
      - run: pip3 install cpplint
      - run: cpplint --exclude vendor/ --recursive . 
